# What we do and why we do it {#whatwedo}

## Philosophy of scientific principles 

**Rigor.** Our most important goal is to produce rigorous science. This does not mean “perfect” or “flawless.” It does mean that we take seriously our responsibility to analyze data to the best of our ability. In service of rigorous science, we will consider potential biases in data collection, analysis, and interpretation. We use whatever tools we can to create results that are replicable. We seek feedback on our work. We do not measure success by counting journal publications or grant dollars, but by our willingness to stand by our findings. 

**Open Science.** We believe that the goals of science are best served when science is open. Open science means that science is (1) accessible and (2) transparent. We benefit from open science. For example, we learn from free tutorials that describe how to use open-source software (`R`, jamovi); we read preprints; we use open data (HRS, MIDUS). Our job as scientists is to ensure our own products are accessible, especially to people outside the academy. This means posting code, data (when possible), and preprints. It means favoring open-source teaching materials, to reduce barriers to learning, and openly-available research tools, to reduce barriers to replicating or reproducing our work. This is what we mean by accessible. An added benefit of posting code and data is that others can see and reproduce all the steps in our analysis, thereby fully understanding our choices and judging for themselves whether we analyzed the data appropriately (and maybe even “optimally"). This is what we mean by transparent. Whenever possible, we will preregister our analyses before working with data and ideally before collecting data (although sometimes this is not feasible [given our work](https://osf.io/x4gzt/)). 

**Diversity.** We conduct science for public benefit and consumption, and this includes all members of the public -- not a select few. As teachers, we wish to impart knowledge to all our students and we strive to ensure all students feel supported in their quest for knowledge. As mentors, we celebrate the variety of backgrounds and perspectives that can enrich our lab and our work. Perhaps most importantly, we will never feel comfortable with the amount of work we have done or are doing to combat systemic racism and sexism in our field and our community, and we will always seek out ways we can be doing more or doing better.

## Chronological and academic history

Sara and David joined the University of Oregon in January 2019, which is when the Personality Is Everywhere Lab was formed. Following the inaugural pi day celebration on March 14, 2019, the lab underwent light renovations during the summer of 2019. We hosted a number of personality researchers during the fall of 2019 (Johanna Hartung, Pat Hill, Colin DeYoung, Dustin Wood) and our first real interview weekend in February of 2020. The lab was fully closed from March to August 2020 in the wake of the COVID-19 pandemic. 

## Things we've been reading

### Papers by the PIE lab

- [Weston et al. (2019). Recommendations for increasing the transparency of analysis of pre-existing data.](articles/weston_etal_2019.pdf)

### Papers etc. by others

- [Goldberg. (1993). The structure of phenotypic traits.](articles/Goldberg-1993-The structure of phenotypic personality traits-.pdf)
- [Roberts et al. (2007). The power of personality.](articles/roberts2007.pdf) -- this is sometimes called the "pig paper" because personality is great.
- [Hampson. (2012). Personality processes: Mechanisms by which personality traits "get outside the skin."](articles/Hampson-2012-Personality Processes- Mechanisms by which Personality Traits “Get Outside the Skin”.pdf)
- [Gelman. (2016). What has happened down here is the winds have changed.](https://statmodeling.stat.columbia.edu/2016/09/21/what-has-happened-down-here-is-the-winds-have-changed/)


