# Roles and expectations{#roles}

## People

### Principal Investigators

**David Condon**

Research interests: personality structure, assessment methods

**Sara Weston**

Research interests: health behaviors and outcomes, personality development 

### Graduate students

**Kendall Mather**

**Sarah McDougald**

**Ian Shryock**

**Dillon Welindt**

**Rachel Jacobson**

**Amala Someshwar**

**Andrew Castillo**

<!-- ### Undergraduate honors students -->

### Undergraduate Research Assistants

Layla Ghazalba

### Alumni

Someday...

## Mentorship philosophy

One of our goals is to help you thrive in your chosen career. This means going beyond the minimum requirements of the graduate program (i.e., classes, first year project, quals, dissertation, etc). We aim to prepare you for the requirements of your career by helping you learn and practice the skills needed to be successful. Our default assumption is that you are seeking a career that involves  research skills. In both academic and industry settings, the skills required to conduct research have much in common. These include:

- Working with data, including data collection, analysis, cleaning, management and storage, and visualization
- Summarizing research in written form and presenting summaries of research to small and large audiences
- Integrating new knowledge into your understanding
- Constructively critiquing research methods, of others and yourself
- Thinking for yourself
- Figuring things out for yourself

There’s a lot to learn in graduate school; most of it is learned and practiced outside of the classroom. We commit to helping you make the most of graduate school by identifying your strengths and areas for growth, and providing opportunities to practice what you need and advance where you can excel. Your training will not look the same as the other students’. We are an individual differences lab, after all. In the process, we will help you pursue research questions that you find interesting and exciting, while guiding you to build a research identity that you can easily communicate to others. 

Because we are both researchers at an R1 institution, our approach to mentorship will necessarily focus on research training. Do not let this deter you from learning more about other careers you can pursue with a Ph.D. Remember our number one goal is that you thrive -- this means not just being good at your future career but that you enjoy doing it. 

In the course of your training, you may occasionally find yourself having to complete tasks that you do not particularly enjoy! For example, nearly every graduate student feels great discomfort presenting research in front of an audience. We will only push you to do things that we strongly believe will help you develop skills or resources that will benefit you in the long run. If you’re feeling uncomfortable about something we’ve asked you to do, come talk to us. We can decide together whether this is worth doing and, if so, how we can help you prepare as best as possible. If you hide your discomfort, we can’t help.

Above all else, communicate with us. Let us know what future you envision for yourself, what your values and goals are, and whenever you change your mind. Let us know what parts of your training are fun and exciting and which parts are boring or scary. Let us know when we’re meeting your needs and when we are not. Whenever possible, name the experience you’re having, even if you don’t have a solution for it. We promise to do the same -- we will give you feedback throughout your time here on where you’re succeeding and where you need to work, and what to focus on moving forward. Be open to feedback. Know that we are open to feedback. Giving feedback requires a surprisingly large amount of time and effort, and feedback should always be accepted with gratitude. Even if you never act on our feedback, always consider it given with respect and the best intentions. We will do the same for you.

### Primary mentors

Your primary mentor will be the PI nominally responsible for your well-being and career success. While both of us will be heavily involved in your training, we believe that the primary-mentor model reduces issues of diffused responsibility and also gives you a “first point of contact” for all your concerns and questions.

Each graduate student will be assigned a primary mentor (either Sara or David) before they arrive on campus. For the first year, this will largely be an arbitrary designation. Graduate students should expect to meet with both PIs regularly during their first year and to collaborate with both mentors on their FYP. We recommend bringing questions to your primary mentor (this will help spread out mentorship work between the PIs) or lab meetings, so we can share knowledge with the entire group.

Towards the end of Spring term during the first year, the student should discuss with Sara and David which PI is the best fit for them personally. This decision should account for research interests as well as mentoring style. Keep in mind that our number one goal is your career success: this is not a conversation about which one of us you like more, but which mentor will best help you flourish. Also keep in mind that on our end, we may push you one way or another, if we feel that either some aspects of fit are more important than others or if we’re in danger of one PI taking on too much primary mentorship. 

You may choose to have both PIs on your committees (FYP, Advising, SAP, Prelims, Dissertation) or just your primary mentor. For all committees, you must have two faculty members outside of the PIE lab. 

### Recommendation Letters

Letters of recommendation are extremely important for getting new positions and grants. You can count on us to write you a letter if you have been in the lab at least two terms. Exceptions can be made if students are applying for fellowships shortly after starting in the lab. 

If you need a letter, notify the ideal letter-writer as soon as possible with the deadline, your CV, and any relevant instructions for the content of the letter. If the letter is for a grant, also include your specific aims. In some cases (especially if short notice is given), you may also be asked to submit a draft of a letter, which will be modified based on our experience with you, made more glamorous, and edited to add anything you left out that we think is important. This will ensure that the letter contains all the information you need, and that it is submitted on time.

### Individual Development Plans (IDPs)

Students are encouraged to regularly complete/update an IDP. A good template is [myIDP](http://myidp.sciencecareers.org/) but students may use another format. IDPs can be used to receive feedback from the mentors on the skills related to their goals (i.e., skills needed for careers of interest) and to facilitate conversations around planning training goals (short- and long-term).

## Expectations

### Principal Investigators

**Research** is our number one priority as faculty. It is the primary basis for our professional evaluations, and it is the primary mechanism for securing funding for the lab. At any given time, we will be involved in writing several manuscripts. Many of these will involve colleagues at other universities. Many will not involve our students. There will be opportunities for us to invite our students to work on such papers, if we know that it is related to their research interests and if we believe they can contribute meaningfully to the paper. To facilitate this, it is important that students keep us aware of their research interests, especially as they change and grow during their graduate career. 

**To graduate students**, we pledge to 

- Be available in person and via email/Slack (see [Communication](#communication)) on a regular basis, including for regular individual meetings
- Provide timely feedback on writing (manuscripts, grant applications, conference abstracts, etc)
- Apply for external finding with the end goal of supporting you financially
- Share our perspective on the state of the field
- Support career development by attempting to  connect you with other researchers, promoting your - work, writing recommendation letters, and financing conference travel (as our budget allows)
- Help you prepare for your next career stage, whether that’s in academia or industry
- Care for your well-being

**To undergraduate honors students**, we pledge to 

- Guide you in preparing a structured project
- Help you find or collect data
- Teach you to analyze and interpret results
- Revise and edit your scientific report
- Meet regularly to discuss progress and pitfalls

**To research assistants**, we pledge to 

- Communicate expectations around your role clearly
- Ensure that you are regularly checking in with either a PI or graduate student
- Compensate work, either monetarily or in the form of research credits

### Graduate Students

**Research** is the most important activity you can engage in as a graduate student. You will learn more doing research than you will in classes or workshops, so do not think of research as something you do instead of or after you have studied an area or a skill. Regarding research, graduate students are expected to:

- Work on projects that help them explore/develop their interests
- Be careful -- this includes checking and double-checking (even triple-checking… quadruple! … you get the idea) preregistrations, analytic code, and drafts. Seeking feedback from others (fellow students, PIs, friends) is part of this process. 
- Always be working on manuscripts for publication. By the time you graduate, you should have multiple publications in the pipeline (published, in press, in review, in preparation). Ideally, you would have one first-authored paper for each year of your program plus a few additional co-authored papers. (Note that this is not the same as doing one paper every year -- your first year will likely not end with you submitting a manuscript, but you should hope to submit multiple  during your fourth and fifth years.) This is aspirational, and not often achieved, but doing so would make you competitive for whatever comes next.
- Develop your dissertation research. This is something to have in the back of your mind at all times, not just at the beginning of your fourth year. Think about the identity you want to have as a research scientist and work on projects that build that reputation. As you develop and work on studies, be thinking of the next research question(s).

**Coursework** is a necessary part of graduate school and, approached wisely, can be very productive. While the UO Psychology program has its course requirements, you can consider the following classes to be required:

- Social/Personality
- Clinical or Developmental Psychology
- Systems Neuroscience or Cognitive Neuroscience
- At least two advanced quantitative courses (including the Data Science specialization in the School of Education, Structural Equation Modeling, Hierarchical Linear Modeling)

Remember that the goal of coursework differs from the goals you had as an undergraduate. No one will look at your transcript, so getting an A is no longer a priority. Instead, your goals should be (1) to identify the information or skills that will be most useful in your research program, (2) invest in understanding that information or those skills to the best of your ability, and (3) do so while spending as little time as possible on homework. If coursework is getting in the way of research, it is no longer supporting your career... it is impeding it. 

**Teaching** is both a requirement and an opportunity in graduate school. Unless we have mountains of funding available, you will be required to GE during most academic terms. This can be an excellent, low-risk way to practice communication, instruction, and working with groups, skills that will be necessary regardless of future career path. Students will benefit from GE-ing for multiple different classes -- this may be more work but can expose them to different teaching styles and types of classes. As a GE, you should consider it your responsibility to attend the class you support, even if the instructor does not require it. Use these opportunities to reflect on what good and bad teaching looks like, how active learning can be incorporated into classes, and what tools or strategies you might implement in a future career. You may consider teaching a summer course as an opportunity for summer funding and also practice. Take this responsibility seriously, but as above, keep efficiency in mind. Please speak to us (David and Sara) if you find that teaching responsibilities are interfering with research. 

**Independence** is a crucial skill for successful researchers. To be clear, independence does not mean that you can complete every stage of a research project perfectly by yourself. But learning how to “figure it out” on your own ensures that when you leave the lab, you’ll have the tools you need to face new challenges and acquire new skills moving forward. In general, we expect our students to do as much as they can on their own and seek us (Sara and David) out when they are stuck. Use your best judgement regarding when this should be. If you need input to move forward, it is your responsibility to seek us out or schedule a meeting (see [Communication](#communication)). Note that your level of independence will change across graduate school -- we expect to provide more regular guidance to new trainees, but by the time you leave the university, you should be able to function independently.

**Be collaborative, not competitive** with the other students in our lab. Science is better when people work together, not tear each other down. Respect your fellow lab-mates. They have strengths and weaknesses that they bring to the table -- you can help them, and they can help you. Respect their culture, their religion, their beliefs, their sexual orientation, their perspective on the world. See every way they differ from you as an opportunity to learn and make your science better. Support your fellow lab-mates. Help them out, even if you’re not a co-author on their project. Allow them to vent if they need it and create space for them if they need it. Help them, and you can expect help in return when you need it. Learn to view the wins of your fellow lab-mates as wins for the PIE lab. 

**Time Management** is critical to success in research, not just as a graduate student, and in life more generally. We (Sara and David) will try to share strategies for time management during lab meetings, but you should feel welcome to ask for these discussions in individual meetings or lab meetings whenever they would be helpful. However, your time is your responsibility. We will neither create schedules for you nor will we tell you what to prioritize, although we may give you feedback when we believe a project is not moving along as quickly as it should. It will be up to you to decide when you work and what you work on. A good starting place is to think of your graduate work as a full time job: 40 hours/week. That being said, you may find that you are able to keep up with coursework and teaching duties while also moving research along in less time -- that's great! Also, you may find yourself working more than 40 hours and not experiencing any issues -- that's great too! The main thing is that you are able to meet your responsibilities, conduct your research, and maintain good mental health.  

**Curiosity** helps you develop your research program, integrate advances in methods and ideas into your work, and provide meaningful contributions in your collaborations and to the field. Be sure to consider the role of curiosity in your research. Resist the temptation to look smart with answers and instead ask questions. Approach every situation you’re in with the goal of learning something new. 

**Have a personal life.**

**Other expectations**

- Present your work at least once a year, ideally more often. Great places to present are  departmental events (e.g., FYP talks, brownbags), other labs, conferences.
- Apply for grants. You can apply for an NSF award during your first or second year and NRSA awards during your fourth and fifth years. Seek out other opportunities to apply for funding or awards. 
- Seek information about all kinds of careers. Consider academia (research and teaching), industry, scientific writing, government research. We (Sara and David) can only really provide you with insight into a few (narrow) - paths, so don’t rely on them for all your information about future careers. Communicate your interests and - values to us, so we can understand what a successful and meaningful career looks like to you. 
- Keep track of your departmental deadlines -- e.g., FYP, SAP, coursework, etc.
- Participate in weekly lab meetings. 
- Attend the Social/Personality brownbag talks. Try to be an active participant, meaning think critically about the information presented to you. Identify the strengths and weaknesses of the study. Evaluate the claims. Be inspired to develop your own research questions out of the work presented. Maybe even ask a question.

**Other things** you might want to know about.

- **Working in other labs** is an excellent way to be exposed to new ideas, new ways of mentoring or doing science, and new people with whom you can form collaborations. This is directly facilitated by the Supporting Area Project, but you’re encouraged to create new collaborations. We recommend being upfront about your interest with other PIs -- are you trying to form a collaboration on a new project or are you just interested in sitting in on lab meetings? Consider yourself a representative of the PIE lab in these collaborations, and be sure to treat the people in these settings with the same respect and curiosity you would treat your fellow lab-mates. 
- **Switching advisors** is permitted for personal or professional reasons. However, such a change must be mutually agreeable to all parties: student, original advisor, and new advisor. Ideally, a change would occur relatively early in a student’s graduate career (first or second year), but this need not be the case. Additionally, students have the option of adding a secondary advisor at any point. Doing this could make a lot of sense if a student’s interests wind up aligning with another faculty member’s expertise, but the student does not wish to make a full change of advisors

### Undergraduate students

**Honors students** are expected to

- Work on their independent project under the mentorship of another lab member (PI or graduate student)
- Check-in weekly with your mentor 
- Schedule time to make progress in your work
- Attend weekly lab meetings
- Present your research to the lab by the end of Spring Term

**Research assistants** are expected to

- Assist other lab members with data collection and analysis
- Develop a weekly work schedule by talking with your mentor. You should be coming to the lab every week and engaging with lab activities for the amount of time associated with your credit hours (3 hours for every credit) or based on your negotiated work load. 
- Discuss career goals with a mentor.

