# Logistics{#logistics}

## Psych IT{#psychit}

Need help with hardware or software? Send a ticket to the Psych IT gurus using the [UO Service Portal](https://service.uoregon.edu/TDClient/2030/Portal/Requests/ServiceCatalog?CategoryID=18258).

## Getting locked out
If you lock your keys in the lab or your office during business hours, Cindy Salmon in the front office may be able to let you into the space. After business hours, a UOPD officer can let you in. To contact them, call (541) 346-2919.

If you get locked in the stairwell after 5:30 pm, a UOPD office can let you back onto the floor. 

## Being in the lab

There are no set times you have to be on campus, in your office or in the lab. Show up to your meetings, show up to classes, show up to seminars, and show up to lab meetings. But you do not need to be here by 9am, and you are not expected to work late. You are expected to get your work done and to be efficient, but you can work efficiently at whatever time of day you like. 

We expect you to spend some time each week working in the lab space (not your office). Being in the lab is a good way of learning from others, helping others, building camaraderie, having fast and easy access to resources (and people) you need, and being relatively free from distractions at home. That said, hours in academia are more flexible than other jobs -- but you should still treat it as a real job (40 hours/week) and show up to the lab. Our primary concern is that you get your work done, so if you find that you are more productive in your assigned office, a coffee shop, or at home (lab-mates can be chatty sometimes), feel free to work in those spaces. If you have no meetings or other obligations that day, it might be a good day to work off campus – but you can’t do this all the time, and we expect to see everyone in the lab on a regular basis. 

## Holidays and vacations

Take them. Planning time off is really important. . Communicate with us when you’ll be taking time off, whether you expect to do no or a little work, and whether you’ll be monitoring email/Slack. 

Before winter and summer break, meet with Sara or David to discuss your work goals and expectations around communication. 

## Remote working

As of writing this, most of our work will be largely remote for the foreseeable future. Please keep in mind that “showing up” still holds when working remotely. If you need any resources to help you be productive from home, please let us know. We may be able to lend you some materials, or we might be able to purchase materials for the lab to lend to you. 
