# Website

## Details

URL: [pielab-science.com](https://pielab-science.com)

Username and password: email Sara or David for this information.

## Purpose

PR for the PIE lab
 - Who's part of the PIE lab
 - What are we currently doing?
 - (If actively recruiting) landing page for new recuirts
 - (If ongoing study) landing page for study participants
 
## Current sections

- [What we study](https://pielab-science.com/research)
- About
- Current lab members (with a page for each)
- Friends of the lab
- [Cooling on the rack](https://pielab-science.com/blog/) (news)
 
## How to update
  - Go to [pielab-science.com/admin](https://pielab-science.com/admin) and log in (see above for username/password details)
  - See sections below for updating specific aspects

### Your Profile
 - Go to the Media section (on the left-hand menu) and click Add New
 - Drop file into box, or select using menus
 - Go to Pages (left-hand menu) and hover over your page -- select Edit with Elementor
 - Use the interface to change text, upload a new picture, include links to other pages, whatever you want!
  
### Your CV
 - Go to the Media section (on the left-hand menu) and click Add New
 - Drop file into box, or select using menus
 - Go to Pages (left-hand menu) and hover over your page -- select Edit with Elementor
 - Hover over the box that contains the text. A pencil will show up in the corner; click on it.
 - On the left-hand side, an Edit Text Editor menu will show up. Find the link to your CV. If you click on it, the link to the PDF will appear. You can either
       - Edit the link to match the new upload (involves changing the year and month of upload and the name of the file as it was uploaded to Wordpress), or
       - Delete the current link to the CV and add a new one with the Add Media button.
 