# External Resources{#external}

## Psychology Department

All the syllabi for all our courses are posted online [here](https://psychology.uoregon.edu/courses/). 

### Graduate Training

- [Psychology Canvas page](https://canvas.uoregon.edu/courses/47465) -- includes list of departmental awards (note that Sara and David do _not_ have access to this page)
- [Coursework and requirements](https://psychology.uoregon.edu/graduate/current-students/doctoral-program/coursework-requirements/)

### Resources

Most of what you’ll need to know about the department is buried [here](https://psyres.uoregon.edu/) somewhere. This includes

- Tech support
- Maintenance issues
- Keys/access
- Reserving rooms
- Graduate Admissions Committee (GAC)
- Graduate Education Committee (GEC)
- Undergraduate Education Committee (UEC)
- Human Subjects (SONA, IRB)
- Department Governance Policies

## Support at the University of Oregon

### Technology

- [Setting up the Virtual Private Network](https://service.uoregon.edu/TDClient/2030/Portal/KB/ArticleDet?ID=31471)
- [Extra advice on the VPN]( https://coehelp.uoregon.edu/how-to-guides/vpn-access-with-cisco-anyconnect/)
- [Downloading free software](https://software.uoregon.edu/) -- you can rely on the university to give access to software that would otherwise cost money, including MS Office and Adobe products.
- [Canvas Support Services](https://service.uoregon.edu/TDClient/2030/Portal/Requests/ServiceDet?ID=38635)

- [UO Library](https://library.uoregon.edu/) -- This is an excellent resource for technology on campus. Some of the IT stuff is actually run through the library and, the staff are super knowledgeable and helpful.

### Financial support
- [Fellowships and Awards](https://gradschool.uoregon.edu/funding/awards)
- [Graduate Student Assistance Fund](https://gradschool.uoregon.edu/funding/special-assistance-funds/assistance-fund)

For students with identities underrepresented:

- [Creating Connections](https://inclusion.uoregon.edu/graduate-support)
- [A Community for Minorities in STEM (CMiS)](https://pages.uoregon.edu/cmis/)
- [Multicultural Center](https://inclusion.uoregon.edu/mcc)
- [Center for Multicultural Academic Excellence (CMAE)](https://inclusion.uoregon.edu/content/center-multicultural-academic-excellence-cmae)
- [LGBTQIA Student Organizations](https://dos.uoregon.edu/lgbt-orgs)
- [LGBT+ in STEM](https://blogs.uoregon.edu/lgbtinstem/lgbtstem-day-2019/)
- [Nontraditional Student Union](https://dos.uoregon.edu/nontrad)
- [Society for the Advancement of Chicanos/Hispanics and Native Americans in Science (SACNAS)](https://uosacnas.uoregon.edu/)

For prospective students

- [Application fee waivers and discounts](https://gradschool.uoregon.edu/admissions/how-to-apply/application-fee-waivers)

### Professional Societies
- [Association for Research in Personality (ARP)](https://www.personality-arp.org)
- [Society for Personality and Social Psychology (SPSP)](http://spsp.org/)
- [Association Psychological Science (APS)](https://www.psychologicalscience.org/)
- [Society for the Improvement of Psychological Science (SIPS)](https://improvingpsych.org/)

