# Useful Links

## R and RMarkdown

### Beginners

- [R for Data Science](https://r4ds.had.co.nz/)
- [YaRrr! The Pirate's Guide to R](https://bookdown.org/ndphillips/YaRrr/) -- this one is great for undergraduates
- [Learning Statistics with R](https://learningstatisticswithr-bookdown.netlify.app/)
- [Cookbook for R](http://www.cookbook-r.com/)
- [R for Psychological Science](http://psyr.djnavarro.net/)

### Cheatsheets

All cheatsheets can be downloaded [here](https://rstudio.com/resources/cheatsheets/).

Especially useful cheatsheets include:

- RMarkdown Reference
- Data Viz
- Transformation
- Iteration
- Purrr
- Stringr

### Data Visualization

- [How to make better spaghetti plots](https://njt-rstudio20.netlify.app/#1)
- [DiagrammR](http://rich-iannone.github.io/DiagrammeR/index.html) -- flowcharts and diagrams
- [DAG models](https://ggdag.malco.io/articles/intro-to-dags.html)

### Markdown

- [RMarkdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/)
  
  - See the section on [Websites](https://bookdown.org/yihui/rmarkdown/websites.html)
  
- [Awesome tables with kable (PDF)](https://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf)
- [Awesome tables with kable (HTML)](http://haozhu233.github.io/kableExtra/awesome_table_in_html.html)
- [How to convert a Google doc to RMarkdown](https://www.storybench.org/convert-google-doc-rmarkdown-publish-github-pages/)
- [Making slides](https://arm.rbind.io/slides/xaringan.html#1)

### GitHub

- [Happy Git with GitHub and R](https://happygitwithr.com/)

### Text Analysis

- [Text mining Twitter with TidyText](https://www.earthdatascience.org/courses/earth-analytics/get-data-using-apis/text-mining-twitter-data-intro-r/) -- includes n-gram network plot
- [Word vectors with tidy data principles](https://www.r-bloggers.com/word-vectors-with-tidy-data-principles/)

### Iteration

- [Purrr](https://emoriebeck.github.io/R-tutorials/purrr/)

### Writing functions

- [Non-standard evaluation](http://adv-r.had.co.nz/Computing-on-the-language.html)

### Reproducibility

- [8 things to make research more findable](http://datacolada.org/69)


## Writing

- [Dan Simons -- writing guide](http://www.dansimons.com/resources/writing_tips.html)
- [EJ Wagenmakers -- Teaching graduate students how to write clearly](http://www.ejwagenmakers.com/2009/TeachingTipsWriting.pdf)
- [Practical Typography](https://practicaltypography.com/)
- [CrossRef](https://doi.crossref.org/simpleTextQuery) -- get DOI's quickly

- [Connected Papers](https://www.connectedpapers.com/) -- find other articles related to a specific research article

## Presentations

- [Public speaking for academics](https://mfr.osf.io/render?url=https%3A%2F%2Fosf.io%2Fd8wm9%2Fdownload)
- [Free PowerPoint templates](https://www.slidescarnival.com/category/free-templates)

## Statistics

### Probability

- [Seeing Theory](https://seeing-theory.brown.edu/)

### Generalized Linear Model

- [Logistic regression is not fucked](http://jakewestfall.org/blog/index.php/2018/03/12/logistic-regression-is-not-fucked/)
- [Melt the clock: tidy time series analysis](https://slides.earo.me/rstudioconf19/#1)

### Machine learning+

- [Statistical rethinking](http://xcelab.net/rm/statistical-rethinking/)
- [Machine learning for psychologists: A gentle introduction](https://github.com/tyarkoni/ML4PS)

- [Specification curves](https://github.com/dcosme/specification-curves/blob/master/SCA_tutorial.md)

### Statistical Power

- [Powering interactions](https://approachingblog.wordpress.com/2018/01/24/powering-your-interaction-2/)
- [Explore researcher degrees of freedom](https://joachim-gassen.github.io/2019/03/explore-your-researcher-degrees-of-freedom/)

## Graduate School

- [The Illustrated Guide to a Ph.D.](http://matt.might.net/articles/phd-school-in-pictures/)

## Life

- Note that being a GE and having a research fellowship are considered different forms of compensation. [Here’s a guide to preparing your (2019) federal taxes](http://pfforphds.com/prepare-grad-student-tax-return/).

