# Conferences{#conf}

Developing a professional network is essential, regardless of career path. Therefore,graduate students are expected to attend national and international meetings and to report on their research at those meetings. Ideally, you would attend two conferences per year, pending available funds, but minimally you should attend one per year (there are typically sufficient department funds available to support this). 

## Conferences we typically attend

- ARP	
- ECP
- SPSP
- APS
- SIPS

## How/why to give a talk

Learning to present your research is important. Very few people will read your papers carefully (sad, but true) but you can reach a lot of people at conference talks and posters. Also, if you plan on staying in academia, getting a post-doc position and getting a faculty position both significantly depend on your ability to present your data. Even if you want to leave academia, presentations are likely to be an important part of your job. Additionally, every time you present your work, you are representing not just yourself but the entire lab.

It is therefore highly encouraged that you seek out opportunities to present your research, whether it is at departmental talk series and events, to other labs (within or outside of UO), at conferences, or to the general public. If you are going to give a presentation (a poster or a talk), be prepared to give a practice presentation to the lab at least one week ahead of time (two weeks or more are advisable for conference presentations, and many weeks ahead of time are advisable for job talks, which require much refining).  Practice talks will help you feel comfortable with your presentation, and will also allow you to get feedback from the lab and implement those changes well in advance of your real presentation. 

Templates for posters will be available, and you can use those as much or as little as you’d like. Some general rules for posters should be followed: minimize text as much as possible (if you wrote a paragraph, you’re doing it wrong), make figures and text large and easy to see at a distance, label your axes, and make sure different colors are easily to discriminate. Other than that, go with your own style.

  * Here's a great set of templates for posters, as well as a philosophy for thinking about them: [Butter Poster](https://derekcrowe.net/butterposter) 
  
## Travel expenses

For any conference expenses that are covered by the lab or the department, you'll need to work with our front office staff to book or reimburse. Here's a general breakdown:

### Conference fees

These should be paid using the department P-card. If it's possible to send an invoice for conference fees, send those to Alison Helzer (ahelzer@uoregon.edu). Or, you can give Alison your log-in information, and she can pay the conference fee on your behalf.

### Flights

Flights should be booked through the Concur system. Before this can happen, you'll need to submit an initial travel request.

See [the department wiki](https://psywiki.uoregon.edu/index.php?title=Psychology/Travel_Policies_and_Procedures) for information on how to submit a travel request (to Alison Helzer) and how to book flights.

### Hotels

Hotels can either be booked through Concur, or you can use a personal credit card and submit the folio for reimbursement via a Concur expense report. 

### Other expenses

This includes parking, taxi/Uber/Lift fees, meals, and other incidentals. Keep you receipts and submit for reimbursement after the conference.


